import re


# Canonical skills with common spellings seen in real resumes. Keeping aliases
# here makes the detector useful even when candidates use shorthand or dots.
SKILL_ALIASES = {
    "Python": ["python", "python3"],
    "Java": ["java"],
    "C++": ["c++", "cpp", "c plus plus"],
    "JavaScript": ["javascript", "js", "ecmascript"],
    "SQL": ["sql", "mysql", "sqlite", "mssql"],
    "HTML": ["html", "html5"],
    "CSS": ["css", "css3", "tailwind"],
    "React": ["react", "reactjs", "react.js"],
    "Node.js": ["node", "nodejs", "node.js"],
    "Django": ["django"],
    "Flask": ["flask"],
    "Ruby": ["ruby", "ruby on rails", "rails"],
    "PHP": ["php"],
    "Swift": ["swift"],
    "Kotlin": ["kotlin"],
    "R": ["r programming", "r language"],
    "MATLAB": ["matlab"],
    "Scala": ["scala"],
    "Go": ["golang", "go language"],
    "TypeScript": ["typescript", "ts"],
    "PostgreSQL": ["postgresql", "postgres", "psql"],
    "MongoDB": ["mongodb", "mongo db", "mongo"],
    "Redis": ["redis"],
    "AWS": ["aws", "amazon web services"],
    "REST API": ["rest api", "restful", "rest api's", "rest apis"],
    "Machine Learning": ["machine learning", "ml model", "ml"],
    "Deep Learning": ["deep learning", "neural network", "neural networks"],
    "Data Analysis": ["data analysis", "data analytics", "data analyst"],
    "Data Visualization": ["data visualization", "data visualisation", "visualization"],
    "Natural Language Processing": ["natural language processing", "nlp"],
    "TensorFlow": ["tensorflow", "tensor flow"],
    "PyTorch": ["pytorch", "py torch"],
    "Pandas": ["pandas"],
    "NumPy": ["numpy", "num py"],
    "Power BI": ["power bi", "powerbi"],
    "Tableau": ["tableau"],
    "Docker": ["docker", "containerization", "containerisation"],
    "Kubernetes": ["kubernetes", "k8s"],
    "Git": ["git", "github", "gitlab", "bitbucket"],
    "C": ["c programming", "c language"],
    "C#": ["c#", "c sharp", "csharp"],
    "Bash": ["bash", "shell scripting", "shell script"],
    "PowerShell": ["powershell", "power shell"],
    "Perl": ["perl"],
    "Dart": ["dart", "flutter"],
    "Rust": ["rust programming", "rust language"],
    "Lua": ["lua"],
    "VBA": ["vba", "visual basic for applications"],
    "Groovy": ["groovy"],
    "Objective-C": ["objective-c", "objective c"],
    "Assembly": ["assembly language", "assembly programming"],
    "Angular": ["angular", "angularjs"],
    "Vue.js": ["vue", "vue.js", "vuejs"],
    "Next.js": ["next.js", "nextjs"],
    "Nuxt.js": ["nuxt", "nuxt.js", "nuxtjs"],
    "Svelte": ["svelte", "sveltekit"],
    "jQuery": ["jquery"],
    "Bootstrap": ["bootstrap"],
    "Sass": ["sass", "scss"],
    "Less": ["less css"],
    "GraphQL": ["graphql", "graph ql"],
    "Webpack": ["webpack"],
    "Vite": ["vite"],
    "Spring": ["spring framework", "spring boot"],
    "ASP.NET": ["asp.net", "asp net", "aspnet"],
    ".NET": [".net", "dotnet", ".net core", "dot net"],
    "FastAPI": ["fastapi", "fast api"],
    "Express.js": ["express.js", "express js", "expressjs"],
    "Laravel": ["laravel"],
    "Symfony": ["symfony"],
    "Hibernate": ["hibernate"],
    "SQLAlchemy": ["sqlalchemy", "sql alchemy"],
    "Celery": ["celery"],
    "gRPC": ["grpc", "g-rpc"],
    "Oracle Database": ["oracle database", "oracle db", "oracle sql"],
    "Microsoft SQL Server": ["microsoft sql server", "sql server", "ms sql server"],
    "MariaDB": ["mariadb", "maria db"],
    "DynamoDB": ["dynamodb", "dynamo db"],
    "Cassandra": ["cassandra"],
    "Elasticsearch": ["elasticsearch", "elastic search", "elk stack"],
    "Firebase": ["firebase"],
    "Neo4j": ["neo4j"],
    "Snowflake": ["snowflake"],
    "BigQuery": ["bigquery", "big query"],
    "Microsoft Azure": ["microsoft azure", "azure cloud", "azure"],
    "Google Cloud": ["google cloud platform", "google cloud", "gcp"],
    "Cloudflare": ["cloudflare", "cloud flare"],
    "Terraform": ["terraform"],
    "Ansible": ["ansible"],
    "Jenkins": ["jenkins"],
    "GitHub Actions": ["github actions"],
    "GitLab CI/CD": ["gitlab ci", "gitlab cicd", "gitlab ci/cd"],
    "Azure DevOps": ["azure devops", "azure pipelines"],
    "CircleCI": ["circleci", "circle ci"],
    "Travis CI": ["travis ci", "travisci"],
    "Argo CD": ["argo cd", "argocd"],
    "Helm": ["helm charts", "kubernetes helm"],
    "Linux": ["linux", "ubuntu", "centos", "red hat"],
    "Nginx": ["nginx"],
    "Apache HTTP Server": ["apache http server", "apache web server"],
    "CI/CD": ["ci/cd", "cicd", "continuous integration", "continuous delivery"],
    "Microservices": ["microservices", "microservice architecture"],
    "Excel": ["microsoft excel", "ms excel", "excel"],
    "Jupyter": ["jupyter", "jupyter notebook"],
    "scikit-learn": ["scikit-learn", "scikit learn", "sklearn"],
    "XGBoost": ["xgboost", "xg boost"],
    "LightGBM": ["lightgbm", "light gbm"],
    "Keras": ["keras"],
    "OpenCV": ["opencv", "open cv"],
    "spaCy": ["spacy", "spa cy"],
    "Hugging Face": ["hugging face", "huggingface"],
    "LangChain": ["langchain", "lang chain"],
    "Large Language Models": ["large language model", "large language models", "llm", "llms"],
    "Generative AI": ["generative ai", "genai", "gen ai"],
    "Computer Vision": ["computer vision", "image classification", "object detection"],
    "Statistics": ["statistics", "statistical analysis", "hypothesis testing"],
    "ETL": ["etl", "extract transform load"],
    "Apache Spark": ["apache spark", "pyspark", "spark sql"],
    "Hadoop": ["hadoop", "hdfs", "mapreduce"],
    "Apache Kafka": ["apache kafka", "kafka"],
    "Apache Airflow": ["apache airflow", "airflow"],
    "dbt": ["dbt", "data build tool"],
    "Databricks": ["databricks"],
    "Looker": ["looker", "looker studio"],
    "Qlik": ["qlik", "qlikview", "qlik sense"],
    "Figma": ["figma"],
    "Adobe XD": ["adobe xd"],
    "Adobe Photoshop": ["adobe photoshop", "photoshop"],
    "Adobe Illustrator": ["adobe illustrator", "illustrator"],
    "UI/UX Design": ["ui/ux", "ux design", "user experience design", "user interface design"],
    "Jira": ["jira", "atlassian jira"],
    "Confluence": ["confluence", "atlassian confluence"],
    "Agile": ["agile methodology", "agile development"],
    "Scrum": ["scrum", "scrum master"],
    "Kanban": ["kanban"],
    "Selenium": ["selenium", "selenium webdriver"],
    "Cypress": ["cypress"],
    "Playwright": ["playwright"],
    "Postman": ["postman", "postman api"],
    "pytest": ["pytest", "py.test"],
    "JUnit": ["junit", "junit 5"],
    "Jest": ["jest", "jestjs"],
    "Linux Administration": ["linux administration", "linux system administration"],
    "Windows Server": ["windows server", "windows administration"],
    "TCP/IP": ["tcp/ip", "tcp ip"],
    "DNS": ["dns", "domain name system"],
    "Active Directory": ["active directory", "azure active directory", "azure ad"],
    "OAuth": ["oauth", "oauth2", "openid connect"],
    "JWT": ["jwt", "json web token"],
    "Cybersecurity": ["cybersecurity", "cyber security", "information security"],
    "SIEM": ["siem", "security information and event management"],
    "Splunk": ["splunk"],
    "Wireshark": ["wireshark"],
    "Salesforce": ["salesforce"],
    "ServiceNow": ["servicenow", "service now"],
    "SAP": ["sap", "sap erp"],
    "Workday": ["workday"],
}

# Kept for callers that need the complete canonical skill catalogue.
skills = list(SKILL_ALIASES)

def extract_skills(text):
    """Return recognised skills, including common aliases and resume spellings."""
    normalized_text = re.sub(r"\s+", " ", text.casefold())
    found_skills = []

    for skill, aliases in SKILL_ALIASES.items():
        for alias in aliases:
            pattern = rf"(?<!\w){re.escape(alias.casefold())}(?!\w)"
            if re.search(pattern, normalized_text):
                found_skills.append(skill)
                break

    return found_skills
